"use client";
import {useEffect,useState} from "react";
import {IconBell,IconCheck,IconX} from "@tabler/icons-react";
import {customerFetch} from "@/lib/customer-session";

type Notice={id?:string;title?:string;message?:string;readAt?:string;createdAt?:string;category?:string};
export function NotificationDrawer(){
  const [open,setOpen]=useState(false); const [items,setItems]=useState<Notice[]>([]); const [unread,setUnread]=useState(0); const [loading,setLoading]=useState(false);
  const load=async()=>{setLoading(true);try{const response=await customerFetch("/api/notifications",{headers:{Accept:"application/json"},cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json() as {items?:Notice[];unread?:number};setItems(data.items??[]);setUnread(data.unread??0);}catch{setItems([]);setUnread(0);}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false);};document.addEventListener("keydown",onKey);return()=>{document.body.style.overflow=previous;document.removeEventListener("keydown",onKey);};},[open]);
  const markRead=async(id:string)=>{await customerFetch(`/api/notifications/${id}/read`,{method:"POST",headers:{Accept:"application/json"}}).catch(()=>{});setItems(current=>current.map(item=>item.id===id?{...item,readAt:new Date().toISOString()}:item));setUnread(current=>Math.max(0,current-1));};
  return <><button className="dashboard-notification-button" type="button" aria-label={unread?`Notifications, ${unread} unread`:"Notifications"} aria-expanded={open} onClick={()=>setOpen(true)}><IconBell size={21} aria-hidden="true"/>{unread>0?<span className="dashboard-notification-count">{unread>99?"99+":unread}</span>:null}</button>{open?<><button className="notification-drawer-scrim" aria-label="Close notifications" type="button" onClick={()=>setOpen(false)}/><aside className="notification-drawer" role="dialog" aria-modal="true" aria-labelledby="notification-drawer-title"><header><div><span className="notification-drawer-eyebrow">Your inbox</span><h2 id="notification-drawer-title">Notifications</h2></div><button type="button" aria-label="Close notifications" onClick={()=>setOpen(false)}><IconX size={20}/></button></header><div className="notification-drawer-body">{loading?<p className="notification-drawer-empty">Loading your latest updates…</p>:items.length===0?<div className="notification-drawer-empty"><IconCheck size={28}/><strong>You’re all caught up</strong><span>Important account and transfer updates will appear here.</span></div>:items.map(item=><article className={`notification-item${item.readAt?" read":""}`} key={item.id??item.createdAt}><div><strong>{item.title??"StrivePay update"}</strong><p>{item.message??"You have a new account update."}</p><small>{item.createdAt?new Date(item.createdAt).toLocaleDateString():"Recently"}</small></div>{item.id&&!item.readAt?<button type="button" aria-label={`Mark ${item.title??"notification"} as read`} onClick={()=>void markRead(item.id!)}><IconCheck size={17}/></button>:null}</article>)}</div></aside></>:null}</>;
}
