"use client";
import {useMemo,useState} from "react";
import {CircleFlag} from "react-circle-flags";
import {IconCheck,IconChevronDown,IconSearch} from "@tabler/icons-react";
import {Modal} from "./modal";
// Keep this list aligned with the countries for which the backend has a Bakkt
// postcode rule, so changing jurisdiction never leads to an un-submittable form.
const COUNTRIES=[["NG","Nigeria","NGN"],["US","United States","USD"],["GB","United Kingdom","GBP"],["AE","United Arab Emirates","AED"],["DE","Germany","EUR"],["FR","France","EUR"],["ES","Spain","EUR"],["IT","Italy","EUR"],["NL","Netherlands","EUR"],["IE","Ireland","EUR"],["AT","Austria","EUR"],["BE","Belgium","EUR"],["DK","Denmark","DKK"],["FI","Finland","EUR"],["GR","Greece","EUR"],["NO","Norway","NOK"],["PL","Poland","PLN"],["PT","Portugal","EUR"],["SE","Sweden","SEK"],["AU","Australia","AUD"],["BR","Brazil","BRL"],["CA","Canada","CAD"],["IN","India","INR"],["JP","Japan","JPY"],["MX","Mexico","MXN"],["NZ","New Zealand","NZD"],["ZA","South Africa","ZAR"],["AR","Argentina","ARS"],["GH","Ghana","GHS"],["KE","Kenya","KES"],["PK","Pakistan","PKR"],["SG","Singapore","SGD"],["TR","Türkiye","TRY"],["UG","Uganda","UGX"],["TZ","Tanzania","TZS"],["ZM","Zambia","ZMW"],["RO","Romania","RON"]] as const;
type CountrySelectProps={value?:string;onChange:(code:string)=>void;label?:string;className?:string;modalClassName?:string};
export function CountrySelect({value,onChange,label="Country",className="",modalClassName=""}:CountrySelectProps){const[open,setOpen]=useState(false),[query,setQuery]=useState("");const selected=COUNTRIES.find(country=>country[0]===value);const visible=useMemo(()=>COUNTRIES.filter(country=>country.join(" ").toLowerCase().includes(query.toLowerCase())),[query]);return <div className={`country-field ${className}`.trim()}><label>{label}</label><button className="country-trigger" type="button" onClick={()=>setOpen(true)}>{selected?<span><span className="country-flag"><CircleFlag countryCode={selected[0].toLowerCase()} height="42" /></span><span><strong>{selected[1]}</strong><small>{selected[0]} · {selected[2]}</small></span></span>:<span className="placeholder">Choose your country</span>}<IconChevronDown className="country-chevron" size={18} stroke={2.2}/></button><Modal open={open} onClose={()=>setOpen(false)} title="Choose your country" description="Search by country name, code or local currency." className={modalClassName}><label className="country-search"><IconSearch size={19} stroke={2}/><input autoFocus placeholder="Search countries" value={query} onChange={event=>setQuery(event.target.value)}/></label><div className="country-grid">{visible.map(country=><button type="button" key={country[0]} className={country[0]===value?"selected":""} onClick={()=>{onChange(country[0]);setOpen(false);setQuery("")}}><span className="country-flag small"><CircleFlag countryCode={country[0].toLowerCase()} height="34" /></span><span><strong>{country[1]}</strong><small>{country[0]} · {country[2]}</small></span>{country[0]===value&&<IconCheck className="country-check" size={19} stroke={2.4}/>}</button>)}</div></Modal></div>}
